### ISSUE TITLE
Serialiser may miss trait calls.

### ISSUE THREAD

**Issue by vext01** [softdevteam/ykrustc#36]
At the time of a dynamic call we don't yet know the set of possible candidates. We'd need to hook the vtable creation code to record them.

[I'm told there are two locations where vtables are generated: once for normal code, once for const code -- bear in mind that normal code can be promoted to const].

**Comment by bjorn3** [comment]
> once for const code

All you need to do in that case is walk all statics and promoted values for function allocs. Eg:

https://github.com/bjorn3/rustc_codegen_cranelift/blob/c4af588f72c317a015f6e26bb7d25ae288096b91/src/constant.rs#L296

For the normal code, you can take a look at:

https://github.com/bjorn3/rustc_codegen_cranelift/blob/c4af588f72c317a015f6e26bb7d25ae288096b91/src/vtable.rs#L95-L113

It is called from https://github.com/bjorn3/rustc_codegen_cranelift/blob/94effb972fa80c89a7d3cf2e209b84b2f301ce3a/src/unsize.rs#L30 when unsizing to a trait object.

Edit: Didn't read your comment on #35: `I've just had a detailed chat with @oli-obk`.

**Comment by vext01** [comment]
> Edit: Didn't read your comment on #35: I've just had a detailed chat with @oli-obk.

Does this mean your suggestion won't work after all?

**Comment by bjorn3** [comment]
No, but I `@oli-obk` may have told you how to do it already.

**Comment by vext01** [comment]
Your method sounds easier ;)

**Comment by vext01** [comment]
@bjorn3 I think I've got the non-const case covered. Something like (this is my WIP fork btw):
https://github.com/vext01/ykrustc_pv/commit/bfb8b35790d7c9861adea67a8e809143cc105a13#diff-657ac9ed61b921713f5039a5236599e8R178-R192

But now I'm trying to figure out the const stuff. It's proving difficult.

The code you linked seems to be cranelift specific, but I think I can hook into `eval_body_using_ecx()`. In my slightly outdated fork, I can get the `AllocId` of the result, but in bleeding edge rustc, the `DefId` is right there:
https://github.com/rust-lang/rust/blob/4be067558962c004b638e4c6f162d50f7c0c98b6/src/librustc_mir/const_eval.rs#L144-L182

I think these are the `DefId`s I'm after (but I'm not totally sure). Does that sound about right?

My plan is to stuff them into a new field in `tcx.sess`.

**Comment by bjorn3** [comment]
https://github.com/bjorn3/rustc_codegen_cranelift/blob/c4af588f72c317a015f6e26bb7d25ae288096b91/src/constant.rs#L255-L269 is used to get the alloc for an static. Then you can use https://github.com/bjorn3/rustc_codegen_cranelift/blob/c4af588f72c317a015f6e26bb7d25ae288096b91/src/constant.rs#L295 to get the target of a relocation (function ptr, static, alloc id of another alloc) within the alloc. I have done it this way since I implemented consts and static a few months ago.

**Comment by vext01** [comment]
I've been trying to get to the bottom of this. I reckon something like this should work:
https://github.com/vext01/ykrustc_pv/commit/51b6d965f5246b9376bd4a81630941cb44b367b4

Here I'm collecting the def ids of methods that enter vtables (and the drop implementations too). Then those def_ids are taken into account when making our serialised IR and the corresponding debug entries. It didn't work :(

So then I though I'd just print the name of the unknown location by using some hard-coding:
```
    // XXX Just prints the problem location's def string manually.
    for c in tcx.crates().iter() {
        if tcx.crate_hash(*c).as_u64() == 4727478737927036944 {
            let xd = DefId{krate: *c, index: DefIndex::from_u32(66)};
            dbg!("XXXXXXXXXXXXXXXXXX");
            dbg!(tcx.def_path_str(xd));
        }
    }
```

The result:
```
[src/librustc_interface/passes.rs:1111] "XXXXXXXXXXXXXXXXXX" = "XXXXXXXXXXXXXXXXXX"
[src/librustc_interface/passes.rs:1112] tcx.def_path_str(xd) = "<yktrace::swt::SWTThreadTracer as yktrace::ThreadTracerImpl>::stop_tracing"
```

So it's definitely related to a trait. And I *think* (because the concrete type seems to be known) that the call has been promoted. So there's probably something wrong with my MIRI vtable hook.

Any ideas @bjorn3 ?

**Comment by bjorn3** [comment]
https://github.com/vext01/ykrustc_pv/commit/51b6d965f5246b9376bd4a81630941cb44b367b4#r34623143

**Comment by vext01** [comment]
This is now fixed. All code-genned items (from both the local and dependent crates) are now serialised into binaries.

This is slow, but it will get us moving for now.
