### ISSUE TITLE
Make tracer choice a runtime decision

### ISSUE THREAD

**Issue by vext01** [softdevteam/ykrustc#51]
As we learned from [this thread](https://github.com/softdevteam/ykrustc/pull/50), if would actually be possible to only compile the standard library (`core`, `std`, more?) twice and re-use the rest of the rust toolchain.

This means we could have a runtime switch for tracer choice, instead of a compile-time one.

I suggest we get a working system before we re-visit this though.

**Comment by ltratt** [comment]
Closing in favour of https://github.com/softdevteam/yk/issues/300.
