### ISSUE TITLE
Optimise SIR encoder/decoder.

### ISSUE THREAD

**Issue by vext01** [softdevteam/ykrustc#58]
Decoding SIR at runtime is painfully slow.

This is because at compile time we simply encode multiple structs one after the other and the runtime then loads them all into a big hashmap on first use.

A better strategy is to mimick what the rustc metadata encoder does. They write an "index" containing a mapping from an identifier to an offset at which the serialised object can be found. If we do the same, we can quickly and lazily load only the data we need into our hashmap.

I was hoping to delay this until the system is more mature, but actually I'm tempted to implement this sooner, as runtime tests are so slow it's stunting productivity.

**Comment by bjorn3** [comment]
Done by https://github.com/softdevteam/yk/pull/163.
